<a href="https://colab.research.google.com/github/Lincoln-Alyson/Lincoln_atividades/blob/main/aula_15_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
brics= pd.read_csv("", index_col=0)
brics

FileNotFoundError: ignored

In [ ]:
brics['area']
#area especifica
brics['area']>8

country_ab
BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
is_huge= brics["area"]>8
brics[brics["area"]>8]

country   capital    area  population
country_ab                                      
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

In [ ]:
import pandas as pd
cars= pd.read_csv("/content/cars (2).csv", index_col= 0)
cars

FileNotFoundError: ignored

In [ ]:
#questão 1
cars['drives_right']
dr=cars['drives_right']
dr

NameError: ignored

In [ ]:
#questão 2
dr['drives_right']

NameError: ignored

In [ ]:
error=50.0
while error > 2:
  error = error/3
  print(error)

16.666666666666668
5.555555555555556
1.851851851851852


In [ ]:
offset = 10
while offset !=0:
  offset = offset-1
  print(offset)

9
8
7
6
5
4
3
2
1
0


In [ ]:
fam=[1.73, 1.68, 1.71, 1.89]
for height in fam:
  print(height)

1.73
1.68
1.71
1.89


In [ ]:
fam=[1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam):
  print("index"+ str(index)+ ":"+ str(height))

index0:1.73
index1:1.68
index2:1.71
index3:1.89


In [ ]:
areas=[11.25, 18.0, 20.0, 10.75, 9.50]
for area in areas:
  print(area)

11.25
18.0
20.0
10.75
9.5


In [ ]:
#questão 1
house= [["hallway", 11.25],
["kitchen", 18.0],
["living room", 20.0],
["bedroom", 10.75],
["bathroom", 9.50]]
for index, house in enumerate(house):
 print("The "+ str(house[0]) + " is " + str(house[1])+ " sqn")

The hallway is 11.25 sqn
The kitchen is 18.0 sqn
The living room is 20.0 sqn
The bedroom is 10.75 sqn
The bathroom is 9.5 sqn


In [ ]:
world= { "afghanistan":30.55,
        "albania":2.77,
        "algeria":39.21 }
for key, value in world.items():
  print(key + " -- " + str(value))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [ ]:
import numpy as np
np_height= np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight= np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi= np_weight / np_height**2
for val in bmi:
  print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [ ]:
import numpy as np
np_height= np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight= np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas= np.array([np_height, np_weight])
for val in meas:
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [ ]:
europe= {'spain':'madrid', 'france':'paris', 'germany':'berlin',
         'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
         'austria':'viena'}
for key, value in europe.items():
  print("The " + " capital " + " of " + key + " is " + str(value))

The  capital  of spain is madrid
The  capital  of france is paris
The  capital  of germany is berlin
The  capital  of norway is oslo
The  capital  of italy is rome
The  capital  of poland is warsaw
The  capital  of austria is viena


In [ ]:
#primeiro item
np_1=[1,2,3,4,5,6,7,8,9,10]
np_2=[11,12,13,14,15,16,17,18,19,20]
conjuntos= np.array([np_1, np_2])
for val in conjuntos:
  print(val)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [ ]:
#segundo item
np_1=[1,2,3,4,5,6,7,8,9,10]
np_2=[11,12,13,14,15,16,17,18,19,20]
conjuntos= np.array([np_1, np_2])
for val in np.nditer(conjuntos):
  print(val)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [ ]:
import pandas as pd
brics= pd.read_csv("brics.csv", index_col=0)
for val in brics:
  print(val)

country
capital
area
population


In [ ]:
brics= pd.read_csv("brics.csv", index_col=0)
for lab, row in brics.iterrows():
  print(lab + ": "+ row["capital"])

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


In [ ]:
brics= pd.read_csv("brics.csv", index_col=0)
for lab, row in brics.iterrows():
brics.loc[lab, "name_length"] = len(row["country"])
  print(brics)

IndentationError: ignored